FROM node:alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:alpine AS builder
WORKDIR /app

ARG RE_CAPTCHA_PROJECT_ID
ARG NEXT_PUBLIC_RE_CAPTCHA_KEY
ARG NEXT_PUBLIC_GA_TRACKING_CODE
ARG NEXT_PUBLIC_HUBSPOT_PORTAL_ID
ARG GOOGLE_APPLICATION_CREDENTIALS
ARG NEXT_PUBLIC_HUBSPOT_CONTACT_EN_FORM
ARG NEXT_PUBLIC_HUBSPOT_CONTACT_ES_FORM
ARG PAYMENT_LINK_API_KEY
ARG PAYMENT_LINK_USERNAME

ENV RE_CAPTCHA_PROJECT_ID $RE_CAPTCHA_PROJECT_ID 
ENV NEXT_PUBLIC_RE_CAPTCHA_KEY $NEXT_PUBLIC_RE_CAPTCHA_KEY
ENV NEXT_PUBLIC_GA_TRACKING_CODE $NEXT_PUBLIC_GA_TRACKING_CODE
ENV NEXT_PUBLIC_HUBSPOT_PORTAL_ID $NEXT_PUBLIC_HUBSPOT_PORTAL_ID
ENV GOOGLE_APPLICATION_CREDENTIALS $GOOGLE_APPLICATION_CREDENTIALS
ENV NEXT_PUBLIC_HUBSPOT_CONTACT_EN_FORM $NEXT_PUBLIC_HUBSPOT_CONTACT_EN_FORM
ENV NEXT_PUBLIC_HUBSPOT_CONTACT_ES_FORM $NEXT_PUBLIC_HUBSPOT_CONTACT_ES_FORM
ENV PAYMENT_LINK_API_KEY $PAYMENT_LINK_API_KEY
ENV PAYMENT_LINK_USERNAME $PAYMENT_LINK_USERNAME
ENV NODE_OPTIONS --openssl-legacy-provider
ENV APP_NAME asoblockchain.org

COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN yarn build && yarn install --production --ignore-scripts --prefer-offline

FROM node:alpine AS runner
WORKDIR /app

ARG RE_CAPTCHA_PROJECT_ID
ARG NEXT_PUBLIC_RE_CAPTCHA_KEY
ARG NEXT_PUBLIC_GA_TRACKING_CODE
ARG NEXT_PUBLIC_HUBSPOT_PORTAL_ID
ARG GOOGLE_APPLICATION_CREDENTIALS
ARG NEXT_PUBLIC_HUBSPOT_CONTACT_EN_FORM
ARG NEXT_PUBLIC_HUBSPOT_CONTACT_ES_FORM
ARG PAYMENT_LINK_API_KEY
ARG PAYMENT_LINK_USERNAME

ENV APP_NAME asoblockchain.org
ENV RE_CAPTCHA_PROJECT_ID $RE_CAPTCHA_PROJECT_ID
ENV NEXT_PUBLIC_RE_CAPTCHA_KEY $NEXT_PUBLIC_RE_CAPTCHA_KEY
ENV NEXT_PUBLIC_GA_TRACKING_CODE $NEXT_PUBLIC_GA_TRACKING_CODE
ENV NEXT_PUBLIC_HUBSPOT_PORTAL_ID $NEXT_PUBLIC_HUBSPOT_PORTAL_ID
ENV GOOGLE_APPLICATION_CREDENTIALS $GOOGLE_APPLICATION_CREDENTIALS
ENV NEXT_PUBLIC_HUBSPOT_CONTACT_EN_FORM $NEXT_PUBLIC_HUBSPOT_CONTACT_EN_FORM
ENV NEXT_PUBLIC_HUBSPOT_CONTACT_ES_FORM $NEXT_PUBLIC_HUBSPOT_CONTACT_ES_FORM
ENV PAYMENT_LINK_API_KEY $PAYMENT_LINK_API_KEY
ENV PAYMENT_LINK_USERNAME $PAYMENT_LINK_USERNAME

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/google-credentials.json ./

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["node_modules/.bin/next", "start"]
